spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      time-to-live: 3d
  data:
    redis:
      port: 6379
      host: localhost
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
easy-query:
  enable: true
  database: mysql
  name-conversion: underlined
  delete-throw: true
  print-sql: true
  default-track: true
  keep-native-style: true

logging:
  level:
    org.springframework.security: info
    root: info

rbac:
  reset: username