spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/training?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 654321
    driver-class-name: org.mariadb.jdbc.Driver
  cache:
    type: redis
    redis:
      time-to-live: 3d
  data:
    redis:
      port: 6379
      host: localhost
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect

easy-query:
  enable: true
  database: mysql
  name-conversion: underlined
  delete-throw: true
  print-sql: true
  default-track: true
  keep-native-style: true

logging:
  level:
    org.springframework.security: info
    root: info
  config: classpath:log4j2.yml

rbac:
  reset: username